services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=springrealm'
      - 'POSTGRES_PASSWORD=docker'
      - 'POSTGRES_USER=docker'
    ports:
      - '5533:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6677:6379'
