spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: ${PGUSER}
    password: ${PGPASSWORD}
    baseline-on-migrate: true
    enabled: true
  # redis:
  #   url: ${REDIS_URL}
  #   host: ${REDISHOST}
  #   port: ${REDISPORT}
  #   user: ${REDISUSER}
  #   password: ${REDISPASSWORD}
