server:
  port: ${SPRING_PORT}
spring:
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: springrealm
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
