server:
  port: 9988
spring:
  profiles:
    active: dev
  application:
    name: springrealm
# springdoc:
#   api-docs:
#     path: /docs
#   swagger-ui:
#     path: /swagger-ui.html
#     operations-sorter: method
