spring:
  datasource:
    url: jdbc:postgresql://localhost:5533/springrealm
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5533/springrealm
    clean-disabled: true
    user: docker
    password: docker
    baseline-on-migrate: true
    enabled: true
