spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: ${PGUSER}
    password: ${PGPASSWORD}
    baseline-on-migrate: true
    enabled: true
  data:
    redis:
      host: ${REDISHOST}
      port: ${REDISPORT}
      username: ${REDISUSER}
      password: ${REDISPASSWORD}
