server:
  servlet:
    context-path: /
  port: 9988
  compression:
    mime-types:
      - application/json
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  application:
    name: springrealm
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-local.xml
