server:
  port: 9988
spring:
  profiles:
    active: ${SPRING_PROFILE}
  application:
    name: springrealm
  cache:
    type: redis
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
