spring:
  datasource:
    url: jdbc:postgresql://localhost:5533/springrealm
    username: docker
    password: docker
    continue-on-error: true
  jpa:
    open-in-view: false
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: 50
